GET http://localhost:8000/
###
GET http://localhost:8000/artists
###
GET http://localhost:8000/genres
###
POST http://localhost:8000/genres
Content-Type: application/json

{
    "name":"fsafa"
}
###
DELETE http://localhost:8000/genres/35
###
GET http://localhost:8000/artist-albums/AC%2FDC
